---
- hosts: 127.0.0.1
  user: bitardo
  sudo: yes
  tasks:
  - user: state=absent name=tours createhome=yes group=jug shell=/bin/bash
  - file: state=absent path=/home/tours owner=tours group=jug mode=0774 
